openapi: 3.1.0
info:
  title: LangSmith Deployment Control Plane Agent Connections (v2) Agent Connections (v2) Integrations (v1) API
  description: 'The LangSmith Deployment Control Plane API is used to programmatically create and manage

    Agent Server deployments. For example, the APIs can be orchestrated to

    create custom CI/CD workflows.


    ## Host

    https://api.host.langchain.com


    ## Authentication

    To authenticate with the LangSmith Deployment Control Plane API, set the `X-Api-Key` header

    to a valid [LangSmith API key](https://docs.langchain.com/langsmith/create-account-api-key#create-an-api-key).


    ## Versioning

    Each endpoint path is prefixed with a version (e.g. `v1`, `v2`).


    ## Quick Start

    1. Call `POST /v2/deployments` to create a new Deployment. The response body contains the Deployment ID (`id`) and the ID of the latest (and first) revision (`latest_revision_id`).

    1. Call `GET /v2/deployments/{deployment_id}` to retrieve the Deployment. Set `deployment_id` in the URL to the value of Deployment ID (`id`).

    1. Poll for revision `status` until `status` is `DEPLOYED` by calling `GET /v2/deployments/{deployment_id}/revisions/{latest_revision_id}`.

    1. Call `PATCH /v2/deployments/{deployment_id}` to update the deployment.

    '
  version: 0.1.0
tags:
- name: Integrations (v1)
paths:
  /v1/integrations/github/install:
    get:
      tags:
      - Integrations (v1)
      summary: List GitHub Integrations
      description: List available GitHub integrations for LangGraph Platfom Cloud SaaS.
      operationId: list_github_integrations_v1_integrations_github_install_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/GithubIntegration'
                type: array
                title: Response List Github Integrations V1 Integrations Github Install Get
      security:
      - API Key: []
      - Tenant ID: []
      - Bearer Auth: []
  /v1/integrations/github/{integration_id}/repos:
    get:
      tags:
      - Integrations (v1)
      summary: List GitHub Repositories
      description: List available GitHub repositories for an integration that are available to deploy to LangSmith Deployment.
      operationId: list_github_repositories_v1_integrations_github__integration_id__repos_get
      security:
      - API Key: []
      - Tenant ID: []
      - Bearer Auth: []
      parameters:
      - name: integration_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
          title: Integration ID
          description: GitHub integration ID.
        description: GitHub integration ID.
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GithubRepository'
                title: Response List Github Repositories V1 Integrations Github  Integration Id  Repos Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v1/integrations/forge/github/install:
    get:
      tags:
      - Integrations (v1)
      summary: List Forge GitHub Integrations
      description: List available Forge GitHub integrations.
      operationId: list_forge_github_integrations_v1_integrations_forge_github_install_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/GithubIntegration'
                type: array
                title: Response List Forge Github Integrations V1 Integrations Forge Github Install Get
      security:
      - API Key: []
      - Tenant ID: []
      - Bearer Auth: []
  /v1/integrations/forge/github/{integration_id}/repos:
    get:
      tags:
      - Integrations (v1)
      summary: List Forge GitHub Repositories
      description: List available GitHub repositories for a Forge integration.
      operationId: list_forge_github_repositories_v1_integrations_forge_github__integration_id__repos_get
      security:
      - API Key: []
      - Tenant ID: []
      - Bearer Auth: []
      parameters:
      - name: integration_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
          title: Integration ID
          description: Forge GitHub integration ID.
        description: Forge GitHub integration ID.
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GithubRepository'
                title: Response List Forge Github Repositories V1 Integrations Forge Github  Integration Id  Repos Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    GithubIntegration:
      properties:
        id:
          type: string
          format: uuid
          title: ID
          description: GitHub Integration ID.<br><br>For example, in the `POST /v2/deployments` request body, set `integration_id` to the value of this field.
        installation_id:
          type: integer
          title: Installation ID
          description: GitHub installation ID.
        name:
          type: string
          title: Name
          description: GitHub accout name.
      type: object
      required:
      - id
      - installation_id
      - name
      title: GithubIntegration
      description: Metadata for a GitHub integration.
    GithubRepository:
      properties:
        host_integration_id:
          type: string
          format: uuid
          title: GitHub Integration ID
          description: GitHub Integration ID.<br><br>For example, in the `POST /v2/deployments` request body, set `integration_id` to the value of this field.
        id:
          type: integer
          title: ID
          description: GitHub repository ID.
        name:
          type: string
          title: Name
          description: GitHub repository name.
        owner:
          type: string
          title: Owner
          description: GitHub repository owner.
        url:
          type: string
          title: URL
          description: GitHub repository URL.<br><br>For example, in the `POST /v2/deployments` request body, set `source_config.repo_url` to the value of this field.
        default_branch:
          type: string
          title: Default Branch
          description: GitHub repository default branch.<br><br>For example, in the `POST /v2/deployments` request body, set `source_revision_config.repo_ref` to the value of this field.
      type: object
      required:
      - host_integration_id
      - id
      - name
      - owner
      - url
      - default_branch
      title: GithubRepository
      description: Metadata for a GitHub repository.
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
  securitySchemes:
    LangSmith API Key:
      type: apiKey
      in: header
      name: X-Api-Key
